name: leaflet
version: 0.0.1-alpha.6
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Mobile-friendly interactive maps
homepage: https://github.com/rwl/leaflet.dart
dependencies:
  intl: any
  pub_semver: '>=1.1.0 <1.2.0'
  quiver: '>=0.18.0 <0.19.0'
  simple_features: any
  uri: '>=0.9.2 <1.0.0'
dev_dependencies:
  browser: any
  unittest: any
