name: leaflet
version: 0.0.1-alpha.1
author: Richard Lincoln <r.w.lincoln@gmail.com>
description: Mobile-friendly interactive maps
homepage: https://github.com/rwl/leaflet.dart
dependencies:
  intl: any
dev_dependencies:
  browser: any
  unittest: any
